In [1]:
import numpy as np

In [9]:
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)


In [10]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

# Question 1


# Yes both the data types are different list_ and array_list have different datatypes

In [11]:
type(list_)

list

In [12]:
type(array_list)

numpy.ndarray

# Question 2

In [13]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [14]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [15]:
array_list = np.array(object = list_, dtype = int)

# Yes after doing above changes there is difference between data types of above code

# Elements in array_list changed to integer and elements in list_ are string

In [19]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [20]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# QUestion 3

In [22]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


In [24]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.shape(num_array)

(2, 3)

In [27]:
np.size(num_array)

6

# Question 4

In [30]:
zero_mat = [[0,0,0],[0,0,0],[0,0,0]]

In [31]:
mat = np.asarray(zero_mat)

In [32]:
mat

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Question 5

In [36]:
identity_mat = np.diag((1,1,1,1,1))

In [37]:
identity_mat

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])